// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HolePunch.Accesses.Repositories
{
    /// <summary>
    /// 服務轉發目標
    /// </summary>
    [Table("service_forward_target", Schema = "holepunch")]
    public partial class ServiceForwardTarget
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 服務ID
        /// </summary>
        [Column("service_id")]
        public int ServiceId { get; set; }
        /// <summary>
        /// 轉發目標名稱
        /// </summary>
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        /// <summary>
        /// IP
        /// </summary>
        [Required]
        [Column("ip_address")]
        [StringLength(255)]
        public string IpAddress { get; set; }
        /// <summary>
        /// 埠號
        /// </summary>
        [Column("port")]
        public int Port { get; set; }
        /// <summary>
        /// 優先權(0最大)
        /// </summary>
        [Column("priority")]
        public int Priority { get; set; }
        /// <summary>
        /// 是否啟用
        /// </summary>
        [Column("enabled")]
        public bool Enabled { get; set; }
    }
}