// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HolePunch.Accesses.Repositories
{
    /// <summary>
    /// 服務
    /// </summary>
    [Table("service", Schema = "holepunch")]
    public partial class Service
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 服務名稱
        /// </summary>
        [Required]
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        /// <summary>
        /// 服務Listen埠號
        /// </summary>
        [Column("port")]
        public int Port { get; set; }
        /// <summary>
        /// 通訊協議(TCP/UDP)
        /// </summary>
        [Required]
        [Column("protocol")]
        [StringLength(16)]
        public string Protocol { get; set; }
        /// <summary>
        /// 服務Logo圖片網址
        /// </summary>
        [Column("logo_url", TypeName = "character varying")]
        public string LogoUrl { get; set; }
        /// <summary>
        /// 是否啟用
        /// </summary>
        [Column("enabled")]
        public bool Enabled { get; set; }
    }
}