// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HolePunch.Accesses.Repositories
{
    /// <summary>
    /// 容許網段
    /// </summary>
    [Table("service_allow_rule", Schema = "holepunch")]
    public partial class ServiceAllowRule
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// 服務ID
        /// </summary>
        [Column("service_id")]
        public int ServiceId { get; set; }
        /// <summary>
        /// 服務轉發目標ID，若為空則表示整個服務
        /// </summary>
        [Column("service_forward_target_id")]
        public int? ServiceForwardTargetId { get; set; }
        /// <summary>
        /// 類型(CIDR_GROUP、CIDR、USER_GROUP、USER)
        /// </summary>
        [Required]
        [Column("type")]
        [StringLength(255)]
        public string Type { get; set; }
        /// <summary>
        /// 網段組
        /// </summary>
        [Column("cidr_group_id")]
        public int? CidrGroupId { get; set; }
        /// <summary>
        /// 網段
        /// </summary>
        [Column("cidr")]
        [StringLength(255)]
        public string Cidr { get; set; }
        /// <summary>
        /// 使用者群組
        /// </summary>
        [Column("user_group_id")]
        public int? UserGroupId { get; set; }
        /// <summary>
        /// 使用者ID
        /// </summary>
        [Column("user_id")]
        public int? UserId { get; set; }
    }
}