import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import {
  CidrGroupService,
  ServiceService,
  UserService
} from './services';
import {
  CidrGroupListCidrGroupResolve,
  CidrGroupCreateCidrGroupResolve,
  CidrGroupUpdateCidrGroupResolve,
  CidrGroupGetCidrGroupResolve,
  CidrGroupDeleteCidrGroupResolve,
  ServiceListServiceResolve,
  ServiceCreateServiceResolve,
  ServiceUpdateServiceResolve,
  ServiceListMyServiceResolve,
  ServiceGetServiceResolve,
  ServiceDeleteServiceResolve,
  ServiceListServiceAllowRuleResolve,
  ServiceCreateServiceAllowRuleResolve,
  ServiceUpdateServiceAllowRuleResolve,
  ServiceGetServiceAllowRuleResolve,
  ServiceDeleteServiceAllowRuleResolve,
  ServiceListServiceForwardTargetResolve,
  ServiceCreateServiceForwardTargetResolve,
  ServiceUpdateServiceForwardTargetResolve,
  ServiceGetServiceForwardTargetResolve,
  ServiceDeleteServiceForwardTargetResolve,
  ServiceListConnectionsResolve,
  UserListUserResolve,
  UserCreateUserResolve,
  UserUpdateUserResolve,
  UserGetUserResolve,
  UserDeleteUserResolve,
  UserListUserGroupResolve,
  UserCreateUserGroupResolve,
  UserUpdateUserGroupResolve,
  UserGetUserGroupResolve,
  UserDeleteUserGroupResolve,
  UserListUserGroupMemberResolve,
  UserAddUserGroupMemberResolve,
  UserRemoveUserGroupMemberResolve,
  UserUpdateWhereUserGroupResolve,
  UserChangeCurrentUserPasswordResolve,
  UserIsAdminResolve,
  UserChangePasswordResolve,
  UserLoginResolve
} from './resolves';

@NgModule({
  declarations: [],
  imports: [CommonModule, HttpClientModule],
  providers: [
    CidrGroupService,
    ServiceService,
    UserService,
    CidrGroupListCidrGroupResolve,
    CidrGroupCreateCidrGroupResolve,
    CidrGroupUpdateCidrGroupResolve,
    CidrGroupGetCidrGroupResolve,
    CidrGroupDeleteCidrGroupResolve,
    ServiceListServiceResolve,
    ServiceCreateServiceResolve,
    ServiceUpdateServiceResolve,
    ServiceListMyServiceResolve,
    ServiceGetServiceResolve,
    ServiceDeleteServiceResolve,
    ServiceListServiceAllowRuleResolve,
    ServiceCreateServiceAllowRuleResolve,
    ServiceUpdateServiceAllowRuleResolve,
    ServiceGetServiceAllowRuleResolve,
    ServiceDeleteServiceAllowRuleResolve,
    ServiceListServiceForwardTargetResolve,
    ServiceCreateServiceForwardTargetResolve,
    ServiceUpdateServiceForwardTargetResolve,
    ServiceGetServiceForwardTargetResolve,
    ServiceDeleteServiceForwardTargetResolve,
    ServiceListConnectionsResolve,
    UserListUserResolve,
    UserCreateUserResolve,
    UserUpdateUserResolve,
    UserGetUserResolve,
    UserDeleteUserResolve,
    UserListUserGroupResolve,
    UserCreateUserGroupResolve,
    UserUpdateUserGroupResolve,
    UserGetUserGroupResolve,
    UserDeleteUserGroupResolve,
    UserListUserGroupMemberResolve,
    UserAddUserGroupMemberResolve,
    UserRemoveUserGroupMemberResolve,
    UserUpdateWhereUserGroupResolve,
    UserChangeCurrentUserPasswordResolve,
    UserIsAdminResolve,
    UserChangePasswordResolve,
    UserLoginResolve
  ]
})
export class SdkModule {
}
