// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

using domain = HolePunch.Domain;

namespace HolePunch.Accesses.Repositories
{
    public partial class CidrGroup
    {
        public static Expression<Func<CidrGroup, domain.CidrGroup>> GetToDomainExpression()
        {
            return (ef) => new domain.CidrGroup() { Id = ef.Id, Name = ef.Name, CidrList = ef.CidrList };
        }

        public static Expression<Func<domain.CidrGroup, CidrGroup>> GetFromDomainExpression()
        {
            return (domain) => new CidrGroup() { Id = domain.Id, Name = domain.Name, CidrList = domain.CidrList };
        }

        public static CidrGroup FromDomain(domain.CidrGroup cidrGroup)
        {
            return GetFromDomainExpression().Compile().Invoke(cidrGroup);
        }

        public domain.CidrGroup ToDomain()
        {
            return GetToDomainExpression().Compile().Invoke(this);
        }
    }
}