// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

using domain = HolePunch.Domain;

namespace HolePunch.Accesses.Repositories
{
    public partial class Service
    {
        public static Expression<Func<Service, domain.Service>> GetToDomainExpression()
        {
            return (ef) => new domain.Service() { Id = ef.Id, Name = ef.Name, Port = ef.Port, Protocol = ef.Protocol, LogoUrl = ef.LogoUrl, Enabled = ef.Enabled };
        }

        public static Expression<Func<domain.Service, Service>> GetFromDomainExpression()
        {
            return (domain) => new Service() { Id = domain.Id, Name = domain.Name, Port = domain.Port, LogoUrl = domain.LogoUrl, Protocol = domain.Protocol, Enabled = domain.Enabled };
        }

        public static Service FromDomain(domain.Service cidrGroup)
        {
            return GetFromDomainExpression().Compile().Invoke(cidrGroup);
        }

        public domain.Service ToDomain()
        {
            return GetToDomainExpression().Compile().Invoke(this);
        }
    }
}