// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

using domain = HolePunch.Domain;

namespace HolePunch.Accesses.Repositories
{
    public partial class ServiceForwardTarget
    {
        public static Expression<Func<ServiceForwardTarget, domain.ServiceForwardTarget>> GetToDomainExpression()
        {
            return (ef) => new domain.ServiceForwardTarget() { Id = ef.Id, ServiceId = ef.ServiceId, Name = ef.Name, IPAddress = ef.IpAddress, Port = ef.Port, Priority = ef.Priority, Enabled = ef.Enabled };
        }

        public static Expression<Func<domain.ServiceForwardTarget, ServiceForwardTarget>> GetFromDomainExpression()
        {
            return (domain) => new ServiceForwardTarget() { Id = domain.Id, ServiceId = domain.ServiceId, Name = domain.Name, IpAddress = domain.IPAddress, Port = domain.Port, Priority = domain.Priority, Enabled = domain.Enabled };
        }

        public static ServiceForwardTarget FromDomain(domain.ServiceForwardTarget cidrGroup)
        {
            return GetFromDomainExpression().Compile().Invoke(cidrGroup);
        }

        public domain.ServiceForwardTarget ToDomain()
        {
            return GetToDomainExpression().Compile().Invoke(this);
        }
    }
}