// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

using domain = HolePunch.Domain;

namespace HolePunch.Accesses.Repositories
{
    public partial class User
    {
        public static Expression<Func<User, domain.User>> GetToDomainExpression()
        {
            return (ef) => new domain.User() { Id = ef.Id, Account = ef.Account, Name = ef.Name, Enabled = ef.Enabled };
        }

        public static Expression<Func<domain.User, User>> GetFromDomainExpression()
        {
            return (domain) => new User() { Id = domain.Id, Account = domain.Account, Name = domain.Name, Enabled = domain.Enabled };
        }

        public static User FromDomain(domain.User cidrGroup)
        {
            return GetFromDomainExpression().Compile().Invoke(cidrGroup);
        }

        public domain.User ToDomain()
        {
            return GetToDomainExpression().Compile().Invoke(this);
        }
    }
}