// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;

using domain = HolePunch.Domain;

namespace HolePunch.Accesses.Repositories
{
    public partial class UserGroup
    {
        public static Expression<Func<UserGroup, domain.UserGroup>> GetToDomainExpression()
        {
            return (ef) => new domain.UserGroup() { Id = ef.Id, Name = ef.Name, IsAdmin = ef.IsAdmin };
        }

        public static Expression<Func<domain.UserGroup, UserGroup>> GetFromDomainExpression()
        {
            return (domain) => new UserGroup() { Id = domain.Id, Name = domain.Name, IsAdmin = domain.IsAdmin };
        }

        public static UserGroup FromDomain(domain.UserGroup cidrGroup)
        {
            return GetFromDomainExpression().Compile().Invoke(cidrGroup);
        }

        public domain.UserGroup ToDomain()
        {
            return GetToDomainExpression().Compile().Invoke(this);
        }
    }
}